import { useState, useCallback, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useCart } from "@/context/CartContext";
import { formatPrice } from "@/data/products";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { motion } from "framer-motion";
import { Trash2, ArrowLeft, ShoppingBag, Banknote, CreditCard, Smartphone, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { trackInitiateCheckout } from "@/lib/fbpixel";
import { useIncompleteOrder } from "@/hooks/useIncompleteOrder";
import { useCustomer } from "@/context/CustomerContext";
import { checkOrderAllowed, getClientIP } from "@/lib/orderControl";
import { useStoreSettings } from "@/hooks/useStoreSettings";

const divisions = [
  "ঢাকা", "চট্টগ্রাম", "রাজশাহী", "খুলনা", "বরিশাল", "সিলেট", "রংপুর", "ময়মনসিংহ",
];

type PaymentMethod = "cod" | "bkash" | "nagad";

const Checkout = () => {
  const { items, subtotal, removeFromCart, clearCart } = useCart();
  const navigate = useNavigate();
  const { user, profile } = useCustomer();
  const [form, setForm] = useState({
    name: "", phone: "", email: "", division: "", district: "", thana: "", address: "",
  });
  const [payment, setPayment] = useState<PaymentMethod>("cod");

  // Autofill from profile
  useEffect(() => {
    if (profile) {
      setForm(f => ({
        ...f,
        name: f.name || profile.full_name || "",
        phone: f.phone || profile.phone || "",
        email: f.email || profile.email || "",
        division: f.division || (profile.default_address as any)?.division || "",
        address: f.address || (profile.default_address as any)?.address || "",
      }));
    }
  }, [profile]);

  const deliveryCharge = subtotal >= 5000 ? 0 : 120;
  const total = subtotal + deliveryCharge;

  const { saveIncomplete, markConverted } = useIncompleteOrder({
    pageSource: "checkout",
    products: items.map((i) => ({
      name: i.product.name,
      id: i.product.id,
      price: i.product.price,
      quantity: i.quantity,
      image: i.product.images[0],
    })),
  });

  const saveTimer = useRef<ReturnType<typeof setTimeout>>();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const newForm = { ...form, [e.target.name]: e.target.value };
    setForm(newForm);

    // Debounced save for incomplete tracking
    if (e.target.name === "name" || e.target.name === "phone" || e.target.name === "email") {
      clearTimeout(saveTimer.current);
      saveTimer.current = setTimeout(() => {
        saveIncomplete({
          name: newForm.name,
          phone: newForm.phone,
          email: newForm.email,
          formData: { division: newForm.division, address: newForm.address },
        });
      }, 2000);
    }
  };

  const [submitting, setSubmitting] = useState(false);
  const { data: storeSettings } = useStoreSettings();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name || !form.phone || !form.address || !form.division) {
      toast.error("সকল প্রয়োজনীয় তথ্য পূরণ করুন");
      return;
    }
    if (submitting) return;
    setSubmitting(true);

    try {
      // Check order control (rate limiting + block check)
      const clientIP = await getClientIP();
      const check = await checkOrderAllowed(form.phone, clientIP);
      if (!check.allowed) {
        const whatsapp = storeSettings?.contactInfo?.whatsapp || "";
        toast.error(check.message, {
          duration: 8000,
          action: whatsapp ? {
            label: "WhatsApp-এ যোগাযোগ",
            onClick: () => window.open(`https://wa.me/${whatsapp}`, "_blank"),
          } : undefined,
        });
        setSubmitting(false);
        return;
      }

      trackInitiateCheckout(items.map(i => ({ id: i.product.id, price: i.product.price, quantity: i.quantity })), total);

      // 1. Insert order (order_number auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          order_number: "",
          customer_name: form.name,
          customer_phone: form.phone,
          customer_email: form.email || null,
          user_id: user?.id || null,
          shipping_address: {
            division: form.division,
            district: form.district,
            thana: form.thana,
            address: form.address,
          },
          payment_method: payment === "cod" ? "ক্যাশ অন ডেলিভারি" : payment === "bkash" ? "bKash" : "Nagad",
          subtotal,
          delivery_charge: deliveryCharge,
          total_amount: total,
          ip_address: clientIP || null,
        })
        .select("id, order_number")
        .single();

      if (orderError) throw orderError;

      // 2. Insert order items
      const orderItems = items.map((i) => ({
        order_id: order.id,
        product_name: i.product.name,
        unit_price: i.product.price,
        quantity: i.quantity,
        total_price: i.product.price * i.quantity,
      }));

      const { error: itemsError } = await supabase.from("order_items").insert(orderItems);
      if (itemsError) throw itemsError;

      // 3. Mark incomplete as converted
      await markConverted(order.id);

      // 4. Success — pass full order data to success page
      clearCart();
      toast.success("অর্ডার সফলভাবে সম্পন্ন হয়েছে!");
      navigate(`/order-success/${order.order_number}`, {
        state: {
          orderNumber: order.order_number,
          customerName: form.name,
          customerPhone: form.phone,
          customerEmail: form.email,
          shippingAddress: {
            division: form.division,
            district: form.district,
            thana: form.thana,
            address: form.address,
          },
          paymentMethod: payment === "cod" ? "ক্যাশ অন ডেলিভারি" : payment === "bkash" ? "bKash" : "Nagad",
          items: items.map((i) => ({
            name: i.product.name,
            image: i.product.images[0],
            quantity: i.quantity,
            unitPrice: i.product.price,
            totalPrice: i.product.price * i.quantity,
          })),
          subtotal,
          deliveryCharge,
          total,
        },
      });
    } catch (err: any) {
      console.error("Order error:", err);
      toast.error("অর্ডার করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।");
    } finally {
      setSubmitting(false);
    }
  };

  if (items.length === 0) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <div className="container flex min-h-[50vh] flex-col items-center justify-center gap-4 py-20">
          <p className="font-bengali text-xl text-muted-foreground">আপনার কার্ট খালি</p>
          <Button onClick={() => navigate("/")} variant="outline" className="rounded-xl">
            <ArrowLeft className="mr-2 h-4 w-4" /> শপিংয়ে ফিরে যান
          </Button>
        </div>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="py-8 md:py-12">
        <div className="container">
          <button onClick={() => navigate(-1)} className="mb-6 flex items-center gap-1 text-sm text-muted-foreground transition-colors hover:text-foreground">
            <ArrowLeft className="h-4 w-4" /> পিছনে যান
          </button>

          <h1 className="mb-8 font-display text-3xl font-extrabold text-foreground md:text-4xl">চেকআউট</h1>

          <form onSubmit={handleSubmit}>
            <div className="grid gap-8 lg:grid-cols-5 lg:gap-12">
              {/* Left: Form */}
              <div className="space-y-8 lg:col-span-3">
                {/* Personal Info */}
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-4 rounded-2xl border bg-card p-6">
                  <h2 className="font-display text-lg font-bold text-card-foreground">ব্যক্তিগত তথ্য</h2>
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div>
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">নাম *</label>
                      <Input name="name" value={form.name} onChange={handleChange} placeholder="আপনার নাম" className="rounded-xl" required />
                    </div>
                    <div>
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">ফোন নাম্বার *</label>
                      <Input name="phone" value={form.phone} onChange={handleChange} placeholder="01XXXXXXXXX" className="rounded-xl" required />
                    </div>
                    <div className="sm:col-span-2">
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">ইমেইল</label>
                      <Input name="email" type="email" value={form.email} onChange={handleChange} placeholder="email@example.com" className="rounded-xl" />
                    </div>
                  </div>
                </motion.div>

                {/* Address */}
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="space-y-4 rounded-2xl border bg-card p-6">
                  <h2 className="font-display text-lg font-bold text-card-foreground">ডেলিভারি ঠিকানা</h2>
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div>
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">বিভাগ *</label>
                      <select name="division" value={form.division} onChange={handleChange} className="flex h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm" required>
                        <option value="">বিভাগ নির্বাচন করুন</option>
                        {divisions.map((d) => <option key={d} value={d}>{d}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">জেলা</label>
                      <Input name="district" value={form.district} onChange={handleChange} placeholder="জেলা" className="rounded-xl" />
                    </div>
                    <div>
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">থানা/উপজেলা</label>
                      <Input name="thana" value={form.thana} onChange={handleChange} placeholder="থানা" className="rounded-xl" />
                    </div>
                    <div className="sm:col-span-2">
                      <label className="mb-1.5 block text-sm font-medium text-muted-foreground">বিস্তারিত ঠিকানা *</label>
                      <textarea
                        name="address"
                        value={form.address}
                        onChange={handleChange}
                        placeholder="বাড়ি নং, রোড, এলাকা..."
                        className="flex min-h-[80px] w-full rounded-xl border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                        required
                      />
                    </div>
                  </div>
                </motion.div>

                {/* Payment */}
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="space-y-4 rounded-2xl border bg-card p-6">
                  <h2 className="font-display text-lg font-bold text-card-foreground">পেমেন্ট মেথড</h2>
                  <div className="grid gap-3 sm:grid-cols-3">
                    {([
                      { id: "cod" as const, label: "ক্যাশ অন ডেলিভারি", icon: Banknote },
                      { id: "bkash" as const, label: "bKash", icon: Smartphone },
                      { id: "nagad" as const, label: "Nagad", icon: CreditCard },
                    ]).map(({ id, label, icon: Icon }) => (
                      <button
                        key={id}
                        type="button"
                        onClick={() => setPayment(id)}
                        className={`flex flex-col items-center gap-2 rounded-xl border-2 p-4 text-sm font-medium transition-all ${
                          payment === id
                            ? "border-accent bg-accent/5 text-foreground"
                            : "border-border text-muted-foreground hover:border-accent/50"
                        }`}
                      >
                        <Icon className="h-6 w-6" />
                        {label}
                      </button>
                    ))}
                  </div>
                </motion.div>
              </div>

              {/* Right: Summary */}
              <div className="lg:col-span-2">
                <div className="lg:sticky lg:top-24">
                  <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="space-y-4 rounded-2xl border bg-card p-6">
                    <h2 className="font-display text-lg font-bold text-card-foreground">অর্ডার সামারি</h2>
                    <div className="space-y-3">
                      {items.map((item) => (
                        <div key={item.product.id} className="flex items-center gap-3">
                          <img src={item.product.images[0]} alt={item.product.name} className="h-14 w-14 rounded-lg object-cover" />
                          <div className="flex-1">
                            <p className="text-sm font-semibold text-card-foreground line-clamp-1">{item.product.name}</p>
                            <p className="text-xs text-muted-foreground">{item.quantity}x {formatPrice(item.product.price)}</p>
                          </div>
                          <p className="font-display text-sm font-bold text-foreground">{formatPrice(item.product.price * item.quantity)}</p>
                          <button type="button" onClick={() => removeFromCart(item.product.id)} className="text-destructive hover:text-destructive/80">
                            <Trash2 className="h-4 w-4" />
                          </button>
                        </div>
                      ))}
                    </div>
                    <div className="space-y-2 border-t pt-4">
                      <div className="flex justify-between text-sm text-muted-foreground">
                        <span>সাবটোটাল</span>
                        <span className="font-semibold text-foreground">{formatPrice(subtotal)}</span>
                      </div>
                      <div className="flex justify-between text-sm text-muted-foreground">
                        <span>ডেলিভারি চার্জ</span>
                        <span className={`font-semibold ${deliveryCharge === 0 ? "text-success" : "text-foreground"}`}>
                          {deliveryCharge === 0 ? "ফ্রি" : formatPrice(deliveryCharge)}
                        </span>
                      </div>
                      {deliveryCharge > 0 && (
                        <p className="text-xs text-muted-foreground">৳৫,০০০+ অর্ডারে ফ্রি ডেলিভারি</p>
                      )}
                      <div className="flex justify-between border-t pt-3">
                        <span className="font-bengali text-base font-bold text-foreground">মোট</span>
                        <span className="font-display text-2xl font-extrabold text-foreground">{formatPrice(total)}</span>
                      </div>
                    </div>
                    <Button type="submit" size="lg" disabled={submitting} className="w-full rounded-xl bg-success py-6 text-base font-bold text-success-foreground shadow-lg hover:bg-success/90">
                      {submitting ? <Loader2 className="mr-2 h-5 w-5 animate-spin" /> : <ShoppingBag className="mr-2 h-5 w-5" />}
                      {submitting ? "অর্ডার হচ্ছে..." : "অর্ডার কনফার্ম করুন"}
                    </Button>
                  </motion.div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Checkout;
